vaadin/vaadin-grid-flow

- src/main/java/com/vaadin/ui/grid/AbstractColumn.java
- src/main/java/com/vaadin/ui/grid/Grid.java
- src/main/java/com/vaadin/ui/grid/GridTemplateRendererUtil.java
- src/test/java/com/vaadin/ui/grid/GridView.java
According to latest changes in Flow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/20)
> Change ComponentRenderer to ComponentTemplateRenderer

- src/main/java/com/vaadin/ui/grid/AbstractColumn.java
- src/main/java/com/vaadin/ui/grid/AbstractGridMultiSelectionModel.java
- src/main/java/com/vaadin/ui/grid/AbstractGridSingleSelectionModel.java
- src/main/java/com/vaadin/ui/grid/ColumnGroup.java
- src/main/java/com/vaadin/ui/grid/Grid.java
And remove redundant generic types
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/24)
> Remove DataGenerator, as it is implemented by AbstractGridExtension

- src/main/java/com/vaadin/ui/grid/AbstractColumn.java
- src/main/java/com/vaadin/ui/grid/Grid.java
- src/main/java/com/vaadin/ui/grid/GridTemplateRendererUtil.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/29)
> Refactor GridTemplateRendererUtil to use the new class TemplateRendererUtil.

- pom.xml
- src/main/java/com/vaadin/ui/grid/Grid.java
- src/test/java/com/vaadin/ui/grid/GridColumnTest.java
- src/test/java/com/vaadin/ui/grid/GridView.java
- src/test/java/com/vaadin/ui/grid/it/GridColumnTest.java
- src/test/java/com/vaadin/ui/grid/it/GridDelegatesToSelectionModelTest.java
- src/test/java/com/vaadin/ui/grid/it/GridFiltering.java
- src/test/java/com/vaadin/ui/grid/it/GridFilteringIT.java
- src/test/java/com/vaadin/ui/grid/it/GridItemRefreshPage.java
- src/test/java/com/vaadin/ui/grid/it/GridItemRefreshPageIT.java
- src/test/java/com/vaadin/ui/grid/it/GridMultiSelectionColumnPage.java
- src/test/java/com/vaadin/ui/grid/it/GridMultiSelectionColumnPageIT.java
- src/test/java/com/vaadin/ui/grid/it/GridMultiSelectionModelTest.java
- src/test/java/com/vaadin/ui/grid/it/GridNoSelectionModelTest.java
- src/test/java/com/vaadin/ui/grid/it/GridPage.java
- src/test/java/com/vaadin/ui/grid/it/GridPageIT.java
- src/test/java/com/vaadin/ui/grid/it/GridPageSizePage.java
- src/test/java/com/vaadin/ui/grid/it/GridPageSizePageIT.java
- src/test/java/com/vaadin/ui/grid/it/GridSelectionModeTest.java
- src/test/java/com/vaadin/ui/grid/it/GridSelectionTest.java
- src/test/java/com/vaadin/ui/grid/it/GridSortingTest.java
- src/test/java/com/vaadin/ui/grid/it/Person.java
- src/test/java/com/vaadin/ui/grid/it/SortOrderBuildersTest.java
and add needed dependencies
so far there will be one more test on sorting needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/32)
> Move more it tests

- pom.xml
- src/test/java/com/vaadin/ui/grid/GridDelegatesToSelectionModelTest.java
- src/test/java/com/vaadin/ui/grid/GridMultiSelectionModelTest.java
- src/test/java/com/vaadin/ui/grid/GridNoSelectionModelTest.java
- src/test/java/com/vaadin/ui/grid/GridSelectionModeTest.java
- src/test/java/com/vaadin/ui/grid/GridSortingTest.java
- src/test/java/com/vaadin/ui/grid/Person.java
- src/test/java/com/vaadin/ui/grid/SortOrderBuildersTest.java
- src/test/java/com/vaadin/ui/grid/it/GridFiltering.java
- src/test/java/com/vaadin/ui/grid/it/GridFilteringIT.java
- src/test/java/com/vaadin/ui/grid/it/GridItemRefreshPage.java
- src/test/java/com/vaadin/ui/grid/it/GridItemRefreshPageIT.java
- src/test/java/com/vaadin/ui/grid/it/GridMultiSelectionColumnPage.java
- src/test/java/com/vaadin/ui/grid/it/GridMultiSelectionColumnPageIT.java
- src/test/java/com/vaadin/ui/grid/it/GridPage.java
- src/test/java/com/vaadin/ui/grid/it/GridPageIT.java
- src/test/java/com/vaadin/ui/grid/it/GridPageSizePage.java
- src/test/java/com/vaadin/ui/grid/it/GridPageSizePageIT.java
redo the PR. move more it tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/35)
> Move more tests about grid to its repo

- src/test/java/com/vaadin/ui/grid/demo/GridView.java
- src/test/java/com/vaadin/ui/grid/tests/GridColumnTest.java
- src/test/java/com/vaadin/ui/grid/tests/GridDelegatesToSelectionModelTest.java
- src/test/java/com/vaadin/ui/grid/tests/GridIT.java
- src/test/java/com/vaadin/ui/grid/tests/GridMultiSelectionModelTest.java
- src/test/java/com/vaadin/ui/grid/tests/GridNoSelectionModelTest.java
- src/test/java/com/vaadin/ui/grid/tests/GridSelectionModeTest.java
- src/test/java/com/vaadin/ui/grid/tests/GridSelectionTest.java
- src/test/java/com/vaadin/ui/grid/tests/GridSortingTest.java
- src/test/java/com/vaadin/ui/grid/tests/GridTestPage.java
- src/test/java/com/vaadin/ui/grid/tests/GridTestPageIT.java
- src/test/java/com/vaadin/ui/grid/tests/Person.java
- src/test/java/com/vaadin/ui/grid/tests/SortOrderBuildersTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/36)
> Refactor the repo structure

- src/test/java/com/vaadin/ui/grid/demo/GridView.java
- src/test/java/com/vaadin/ui/grid/tests/GridIT.java
- src/test/java/com/vaadin/ui/grid/tests/GridTestPageIT.java
Depends on https://github.com/vaadin/flow/pull/3144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/44)
> Add a demo and test for basic renderers.

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/java/com/vaadin/flow/component/grid/GridTemplateRendererUtil.java
- src/main/resources/META-INF/resources/frontend/flow-grid-component-renderer.html
- src/test/java/com/vaadin/flow/component/grid/it/GridItemRefreshPageIT.java
Also this update changes how the flow-grid-component-renderer behaves, fixing visual bugs and enabling tests that were previously ignored.
This patch depends on https://github.com/vaadin/flow/issues/3195
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/49)
> Extract common logic about ComponentRenderer from Grid to make it reusable for other components

- src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java
- src/main/java/com/vaadin/flow/component/grid/ColumnGroup.java
- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/tests/GridColumnTest.java
- src/test/java/com/vaadin/flow/component/grid/tests/GridIT.java
- src/test/java/com/vaadin/flow/component/grid/tests/GridSortingTest.java
- src/test/java/com/vaadin/flow/component/grid/tests/GridTestPage.java
- src/test/java/com/vaadin/flow/component/grid/tests/GridTestPageIT.java
Also add tests and change the BeanGrid demo to remove columns instead of just hiding them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/54)
> Add removeColumn and removeColumnByKey methods to Grid.

- src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java
- src/main/java/com/vaadin/flow/component/grid/ColumnBase.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/tests/GridIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/55)
> Remove setHidden and override setVisible

- src/test/java/com/vaadin/flow/component/grid/BeanGridTest.java
- src/test/java/com/vaadin/flow/component/grid/GridColumnTest.java
- src/test/java/com/vaadin/flow/component/grid/GridDelegatesToSelectionModelTest.java
- src/test/java/com/vaadin/flow/component/grid/GridMultiSelectionModelTest.java
- src/test/java/com/vaadin/flow/component/grid/GridNoSelectionModelTest.java
- src/test/java/com/vaadin/flow/component/grid/GridSelectionModeTest.java
- src/test/java/com/vaadin/flow/component/grid/GridSelectionTest.java
- src/test/java/com/vaadin/flow/component/grid/GridSortingTest.java
- src/test/java/com/vaadin/flow/component/grid/Person.java
- src/test/java/com/vaadin/flow/component/grid/SortOrderBuildersTest.java
- src/test/java/com/vaadin/flow/component/grid/it/GridFilteringPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridTestPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridTestPageIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridUpdateDataProviderIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridUpdateDataProviderPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/56)
> Move ITs to the it package, moved unit tests to the root package

- src/test/java/com/vaadin/flow/component/grid/GridMultiSelectionModelTest.java
- src/test/java/com/vaadin/flow/component/grid/GridSortingTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/37)
> Remove redundant generics types

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/60)
> Update generated components and add lumo style to demos

- src/main/resources/META-INF/resources/frontend/gridConnector.js
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridVirtualScrolling.java
- src/test/java/com/vaadin/flow/component/grid/it/GridVirtualScrollingIT.java
Fixes #14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/66)
> Correctly calculate page to retrieve from the server

- src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java
- src/main/java/com/vaadin/flow/component/grid/ColumnBase.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/72)
> Remove the support for renderers on headers and footers

- src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/resources/META-INF/resources/frontend/gridConnector.js
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridFilteringIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/77)
> Only refresh changed item not all items.

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/java/com/vaadin/flow/component/grid/GridSortOrder.java
- src/test/java/com/vaadin/flow/component/grid/GridSortingTest.java
If they equal do not do anything for sort request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/80)
> Check if existing sort order equals new sort order.

- pom.xml
- src/test/java/com/vaadin/flow/component/grid/it/GridItemRefreshPageIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/90)
> Add version for Grid webjar

- pom.xml
- src/test/java/com/vaadin/flow/component/grid/it/GridInATemplate.java
- src/test/java/com/vaadin/flow/component/grid/it/GridWithTemplateIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridWithTemplatePage.java
- src/test/java/com/vaadin/flow/component/grid/it/TestTemplate.java
- src/test/webapp/frontend/src/grid-in-a-template.html
- src/test/webapp/frontend/src/test-template.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/94)
> Add tests for Grid interacting with PolymerTemplates

- src/main/resources/META-INF/resources/frontend/gridConnector.js
When scrolling down the Grid with the first item selected, the item was losing the selection, breaking an integration test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/98)
> Fix selection on grid when scrolling

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/resources/META-INF/resources/frontend/gridConnector.js
- src/test/java/com/vaadin/flow/component/grid/it/GridPageSizePage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridPageSizePageIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/97)
> Make setPageSize public

- src/test/java/com/vaadin/flow/component/grid/it/GridWithTemplateIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridWithTemplatePage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/100)
> Add tests for column properties on Grid injected by @Id

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridFilteringPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridItemRefreshPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridPageSizePage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridTestPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridUpdateDataProviderPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridVirtualScrollingPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridWithTemplatePage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/101)
> Now the details row is properly updated when the model item is refreshed

- pom.xml
I updated grid webjars also
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/103)
> Use latest grid-5.0.0-beta2 and text-field-2.0.0-beta2

- src/main/java/com/vaadin/flow/component/grid/Grid.java
This way it won't make the items disappear.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/102)
> Set multi-sort as attribute not property.

- src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/GridMultiSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/GridSelectionColumn.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Fixes #48
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/104)
> Extend API with methods to allow freeze selection column

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/it/GridTestPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridTestPageIT.java
Closes #91
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/110)
> Synchronize 'size' property.

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/it/GridLoadsItemsIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridLoadsItemsPage.java
Requries vaadin/flow#3635
Fixes #109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/111)
> Init client side based on array updater API

- pom.xml
- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/it/GridLoadsItemsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/118)
> Update vaadin-grid to beta6 and text-field to beta3

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
Added addComponentColumn, which is the same as in V8.
Clarified javadocs for addColumn methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/119)
> Make adding component columns easier

- src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/121)
> Fixes after componentsupplier got removed from flow

- src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/java/com/vaadin/flow/component/grid/GridMultiSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/GridNoneSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/GridSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/GridSingleSelectionModel.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/124)
> Update due changes in Flow SelectionEvent

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/GridSortingTest.java
Fixes #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/125)
> Respect null values in the Column::setComparator(ValueProvider) method

- src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/128)
> Fix failing compilation due to faulty override.

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/131)
> Update webcomponent to 5.0.0-beta7

- src/test/java/com/vaadin/flow/component/grid/it/GridOnFlexLayoutIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridOnFlexLayoutPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/140)
> Add a test for a full sized Grid inside a FlexLayout

- src/test/java/com/vaadin/flow/component/grid/it/GridFullSizeInATemplateIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridFullSizeInATemplatePage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridInATemplate.java
- src/test/java/com/vaadin/flow/component/grid/it/GridSizeIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/141)
> Add a test for full-size Grid inside a template

- src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/143)
> Add missing method implementations.

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/it/GridSerializationIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridSerializationPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/142)
> addColumn(ValueProvider) now converts the item to String instead of JSON

- src/main/java/com/vaadin/flow/component/grid/Grid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/149)
> Renamed onEnableStateChange to onEnableStateChanged

- src/test/java/com/vaadin/flow/component/grid/it/GridUpdateDataProviderIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridUpdateDataProviderPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/152)
> Add IT for swaping DataProviders that return different objects with same ID

- src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Also add a safeguard on GridViewIT to make the ComponentRenderer tests more reliable on CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/156)
> Port the MultiSelect API from FW8, and update demo

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/160)
> Update vaadin-grid to 5.0.0-beta8

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes #150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/162)
> Use correct location for connector

- src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java
fixes #65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/161)
> Remove HasStyle from Grid-AbstractColumn

- src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java
- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/GridColumnTest.java
Fix for #139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/164)
> Try to compare result of value provider based on the common type

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/174)
> Update vaadin-grid to 5.0.3

- src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java
Makes things compile again after vaadin/flow#4003
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/168)
> Update selection models to work with simplified HasValue

- pom.xml
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/190)
> Update vaadin-grid to 5.0.4

- src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/192)
> Fix after flow#4100

- src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java
Fixes #4111
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193)
> Correct single argument "select" method implementation

- src/main/java/com/vaadin/flow/component/grid/AbstractRow.java
- src/main/java/com/vaadin/flow/component/grid/ColumnLayer.java
Fixes #198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/205)
> Make classes Serializable

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/BeanGridTest.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This method can be used only with a bean-grid. It removes existing
columns and adds new columns for the given property names in the given
order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/204)
> Add setColumns(String... propertyNames) method

- pom.xml
- src/main/java/com/vaadin/flow/component/grid/AbstractRow.java
- src/test/java/com/vaadin/flow/component/grid/GridSerializableTest.java
Related to vaadin/platform#173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/210)
> Make classes serializable, add test

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/resources/META-INF/resources/frontend/gridConnector.js
- src/test/java/com/vaadin/flow/component/grid/BeanGridTest.java
- src/test/java/com/vaadin/flow/component/grid/PropertyRetrospectionTest.java
- src/test/java/com/vaadin/flow/component/grid/it/ButtonInGridIT.java
- src/test/java/com/vaadin/flow/component/grid/it/ButtonInGridPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
- src/test/java/com/vaadin/flow/component/grid/it/TextRendererIT.java
- src/test/java/com/vaadin/flow/component/grid/it/TextRendererPage.java
Rebased tree-grid with master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/225)
> tree-grid rebase

- src/test/java/com/vaadin/flow/component/grid/it/ButtonInGridIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/226)
> Disable test for reverted fix.

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/231)
> Fix type pom on the wrong dependency

- README.md
- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/238)
> Update to 1.1-SNAPSHOT version

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/244)
> Add 1.1 branch for TreeGrid

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/242)
> Add branch for 1.0 with TreeGrid

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/243)
> 1.0 readme

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/GridColumnTest.java
added getter for Renderer passed in Column constructor, implements #197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/251)
> Renderer getters

- src/main/java/com/vaadin/flow/component/grid/Grid.java
Demo for using the theme variant will be added later with all the other components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/258)
> Correct the Theme Variant APIs

- pom.xml
- src/main/java/com/vaadin/flow/component/grid/Grid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/262)
> Fix critical SonarQube warnings

- src/main/java/com/vaadin/flow/component/grid/GridVariant.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/263)
> Update generated theme variant

- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Extends the waiting time, hopefully will make the test stable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/264)
> Make grid componentRenderer test stable.

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/resources/META-INF/resources/frontend/gridConnector.js
- src/test/java/com/vaadin/flow/component/grid/GridColumnTest.java
- src/test/java/com/vaadin/flow/component/grid/it/ButtonInGridIT.java
Reverts vaadin/vaadin-grid-flow#259
it contains API changes, need to be reverted
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/267)
> Revert "Maintenance release picks"

- src/main/resources/META-INF/resources/frontend/gridConnector.js
- src/test/java/com/vaadin/flow/component/grid/it/ButtonInGridIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/268)
> Grid 1.0.1 maintenance release picks

- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/272)
> Add demo for theme variant usage

- pom.xml
- src/main/java/com/vaadin/flow/component/grid/GridSortOrder.java
- src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/273)
> Remove commons-lang3 dependency

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/BeanGridSortingTest.java
- src/test/java/com/vaadin/flow/component/grid/it/BeanGridSortingIT.java
- src/test/java/com/vaadin/flow/component/grid/it/BeanGridSortingPage.java
Cherry-pick from master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/278)
> Remove unnecessary conversion of bean properties to string (#277)

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/BeanGridSortingTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/280)
> Add setSortableColumns method

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/BeanGridSortingTest.java
- src/test/java/com/vaadin/flow/component/grid/it/BeanGridSortingPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/285)
> Make automatic columns sortable by default if the property is Comparable

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/BeanGridSortingTest.java
- src/test/java/com/vaadin/flow/component/grid/it/BeanGridSortingPage.java
Cherry-picked from master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/286)
> Make automatic columns sortable by default if the property is Comparable (#285)

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/BeanGridTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/288)
> Add addColumns method and Grid(Class, boolean) constructor

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/resources/META-INF/resources/frontend/gridConnector.js
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/290)
> Add the sort method

- src/test/java/com/vaadin/flow/component/grid/it/RefreshAndMakeVisibleGridIT.java
- src/test/java/com/vaadin/flow/component/grid/it/RefreshAndMakeVisibleGridPage.java
- src/test/java/com/vaadin/flow/component/grid/it/SelectAndMakeVisibleIT.java
- src/test/java/com/vaadin/flow/component/grid/it/SelectAndMakeVisiblePage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/291)
> IT test for flow bug #4444, #4438

- src/test/java/com/vaadin/flow/component/grid/it/ToggleVisibilityIT.java
- src/test/java/com/vaadin/flow/component/grid/it/ToggleVisibilityPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/298)
> Add an IT for Flow#4448 using Grid

- src/test/java/com/vaadin/flow/component/grid/it/RefreshAndMakeVisibleGridIT.java
- src/test/java/com/vaadin/flow/component/grid/it/RefreshAndMakeVisibleGridPage.java
- src/test/java/com/vaadin/flow/component/grid/it/SelectAndMakeVisibleIT.java
- src/test/java/com/vaadin/flow/component/grid/it/SelectAndMakeVisiblePage.java
* IT test for flow bug #4444
* Add one more test to check that #4438 is fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/293)
> IT test for flow bug #4444, #4438 (#291)

- src/test/java/com/vaadin/flow/component/grid/it/ToggleVisibilityIT.java
- src/test/java/com/vaadin/flow/component/grid/it/ToggleVisibilityPage.java
* Add an IT for Flow#4448 using Grid
Cherry-picked from master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/299)
> Add an IT for Flow#4448 using Grid (#298)

- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
* Make grid componentRenderer test stable.
Extend waiting time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/305)
> Make grid componentRenderer test stable. (#264)

- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
* Clone demo-beans to fix ITs
The ITs are failing because somehow editing a Person bean in one view
changes the same Person in another view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/306)
> Clone demo-beans to fix ITs (#292)

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/302)
> Update readme about no V11

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/308)
> Depend on all WebJars explicitly to avoid version ranges in resulting jars (#256)

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Fixes #318
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/319)
> Add IT test for #318 (#317)

- pom.xml
- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/java/com/vaadin/flow/component/grid/GridContextMenu.java
- src/main/resources/META-INF/resources/frontend/gridConnector.js
- src/test/java/com/vaadin/flow/component/grid/GridContextMenuTest.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/ContextMenuGridIT.java
- src/test/java/com/vaadin/flow/component/grid/it/ContextMenuGridPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
* Add context-menu integration
* Add addItem(Component) overload
* Formatting
* Add copyright and a unit test
* Resolve minor review comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/328)
> Add GridContextMenu (#271)

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/329)
> Update component version to 1.2-SNAPSHOT

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/330)
> Update Readme about 1.2 branch

- README.md
Part of vaadin-button-flow#83
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/343)
> Fix documentation link (#342)

- src/main/java/com/vaadin/flow/component/grid/GridVariant.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/346)
> Update java wrapper to stable version

- pom.xml
Fixes #339
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/349)
> Add required for demo class into the demo jar

- pom.xml
Fixes #339
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/350)
> Add required for demo class into the demo jar (#349)

- src/test/java/com/vaadin/flow/component/grid/it/HeaderTextIT.java
- src/test/java/com/vaadin/flow/component/grid/it/HeaderTextPage.java
- src/test/java/com/vaadin/flow/component/grid/testbench/GridElement.java
Fixes #155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/356)
> Adding tests for changing header text

- src/test/java/com/vaadin/flow/component/grid/it/HeaderTextIT.java
- src/test/java/com/vaadin/flow/component/grid/it/HeaderTextPage.java
- src/test/java/com/vaadin/flow/component/grid/testbench/GridElement.java
- src/test/java/com/vaadin/flow/data/bean/Address.java
- src/test/java/com/vaadin/flow/data/bean/Country.java
- src/test/java/com/vaadin/flow/data/bean/Gender.java
- src/test/java/com/vaadin/flow/data/bean/Person.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/360)
> Cherry pick from master pr356

- pom.xml
- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/java/com/vaadin/flow/component/grid/ItemClickEvent.java
- src/main/java/com/vaadin/flow/component/grid/ItemDoubleClickEvent.java
- src/main/resources/META-INF/resources/frontend/gridConnector.js
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/DisabledGridIT.java
- src/test/java/com/vaadin/flow/component/grid/it/DisabledGridPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
- src/test/java/com/vaadin/flow/component/grid/it/ItemClickListenerIT.java
- src/test/java/com/vaadin/flow/component/grid/it/ItemClickListenerPage.java
Implementation for #195
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/359)
> Allow register item click and item double click listeners

- src/main/java/com/vaadin/flow/component/grid/Editor.java
- src/main/java/com/vaadin/flow/component/grid/EditorCancelEvent.java
- src/main/java/com/vaadin/flow/component/grid/EditorCancelListener.java
- src/main/java/com/vaadin/flow/component/grid/EditorImpl.java
- src/main/java/com/vaadin/flow/component/grid/EditorOpenEvent.java
- src/main/java/com/vaadin/flow/component/grid/EditorOpenListener.java
- src/main/java/com/vaadin/flow/component/grid/EditorSaveEvent.java
- src/main/java/com/vaadin/flow/component/grid/EditorSaveListener.java
- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/BeanGridTest.java
- src/test/java/com/vaadin/flow/component/grid/EditorImplTest.java
- src/test/java/com/vaadin/flow/component/grid/GridColumnTest.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Add basic features for Grid editor.
Fix for #357 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/363)
> Grid Editor basic functionality

- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/369)
> Correct Femail

- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Fixes #370
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/371)
> Rename column in demo and correct IT tests

- src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandCollapseRecursivelyIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/385)
> Make TreeGridExpandCollapseRecursivelyIT more stable

- src/main/java/com/vaadin/flow/component/grid/Grid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/389)
> Fix serialization errors with the UpdateQueue

- src/main/java/com/vaadin/flow/component/grid/Grid.java
Cherry-pick of https://github.com/vaadin/vaadin-grid-flow/pull/389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/391)
> Fix serialization errors with the UpdateQueue (#389)

- src/main/java/com/vaadin/flow/component/grid/ColumnBase.java
- src/main/java/com/vaadin/flow/component/grid/ColumnTextAlign.java
- src/test/java/com/vaadin/flow/component/grid/GridColumnTest.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
See #146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/388)
> Add support for the textAlign property on columns

- src/test/java/com/vaadin/flow/component/grid/it/TemplateRendererEventHandlerIT.java
- src/test/java/com/vaadin/flow/component/grid/it/TemplateRendererEventHandlerPage.java
The fix is in Flow repo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/396)
> IT test for #4054

- src/test/java/com/vaadin/flow/component/grid/demo/BeanGenerator.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/demo/ItemGenerator.java
- src/test/java/com/vaadin/flow/component/grid/demo/PeopleGenerator.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This patch introduces a Random instance per bean field, fixing the
problem of having variance in the data every time a new field is added
to the bean for demonstration purposes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/403)
> Make the data for the demo more stable

- src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Fixes #387
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/407)
> Set select all to selected if all items selected.

- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Fixes #408
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/409)
> Pressing escape in the open editor closes it with cancel.

- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Fixes #406
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/410)
> Close not-buffered editor using Tab

- src/main/java/com/vaadin/flow/component/grid/ColumnPathRenderer.java
- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/java/com/vaadin/flow/component/grid/editor/EditorRenderer.java
- src/main/resources/META-INF/resources/frontend/gridConnector.js
- src/test/java/com/vaadin/flow/component/grid/it/ColumnPathIT.java
- src/test/java/com/vaadin/flow/component/grid/it/ColumnPathPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/411)
> Add support for the path property on Columns

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/420)
> Use Flow 1.3-SNAPSHOT

- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/demo/PeopleGenerator.java
They are not being used by any demo, and are causing problems on `vaadin.com`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/421)
> Remove Country and State fields from Person

- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/demo/PeopleGenerator.java
They are not being used by any demo, and are causing problems on
vaadin.com
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/422)
> Remove Country and State fields from Person (#421)

- src/main/java/com/vaadin/flow/component/grid/editor/Editor.java
Fixes #414
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/416)
> Update JavaDoc to describe functionality.

- src/main/java/com/vaadin/flow/component/grid/editor/Editor.java
- src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/editor/EditorImplTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/418)
> Add closeEditor method for use in unbuffered mode.

- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Add tests for #404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/423)
> Makes editor tests check for focused field on open

- src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java
- src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/java/com/vaadin/flow/component/grid/editor/Editor.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
- src/test/java/com/vaadin/flow/component/grid/it/HiddenColumnIT.java
- src/test/java/com/vaadin/flow/component/grid/it/HiddenColumnPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/426)
> Cherry pick fixes for 2.1 from master

- src/test/java/com/vaadin/flow/component/grid/GridSerializableTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/443)
> Adding osgi classes to excluded patterns in serializable test

- pom.xml
- src/main/java/com/vaadin/flow/component/grid/osgi/GridContributor.java
Fixes #440
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/449)
> Add Grid static web resources OSGi contributor

- pom.xml
- src/main/java/com/vaadin/flow/component/grid/osgi/GridContributor.java
Fixes #440
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/454)
> Add Grid static web resources OSGi contributor (#449)

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/main/java/com/vaadin/flow/component/grid/GridMultiSelectionModel.java
- src/main/java/com/vaadin/flow/component/grid/GridSortOrderBuilder.java
- src/main/java/com/vaadin/flow/component/grid/ItemClickEvent.java
- src/main/java/com/vaadin/flow/component/grid/ItemDoubleClickEvent.java
- src/main/java/com/vaadin/flow/component/grid/editor/Editor.java
- src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/455)
> fixed javadoc compilation errors and warnings

- src/main/java/com/vaadin/flow/component/grid/Grid.java
- src/test/java/com/vaadin/flow/component/grid/it/GridEditorRefreshIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridEditorRefreshPage.java
Fixes #417
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/460)
> Close editor whenever the data provider is changed or updated (#447)

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/456)
> removed obsolete version

- src/main/resources/META-INF/resources/frontend/gridConnector.js
- src/test/java/com/vaadin/flow/component/grid/it/ChangingDataSizeIT.java
- src/test/java/com/vaadin/flow/component/grid/it/ChangingDataSizePage.java
Part of https://github.com/vaadin/flow/issues/3830
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/473)
> Add IT for DataProvider changing in size over time

- src/test/java/com/vaadin/flow/component/grid/demo/GridDemo.java
Changing and formatting the demos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/475)
> Formatting changes

- pom.xml
- src/main/java/com/vaadin/flow/component/grid/ColumnPathRenderer.java
- src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
- src/test/java/com/vaadin/flow/component/grid/it/GridPageSizePageIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Fixes #477
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/488)
> No header row should be added if not defining column header(s).

- vaadin-grid-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/496)
> Pin versions for transitive dependencies

- vaadin-grid-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/503)
> vaadin-grid 5.3.0

- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Fixes breakage caused by `context-menu` update + fix for a flaky test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/505)
> Test fixes

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/530)
> Update to Flow 1.4-SNAPSHOT

- pom.xml
- vaadin-grid-flow-demo/pom.xml
- vaadin-grid-flow-integration-tests/pom.xml
- vaadin-grid-flow-testbench/pom.xml
- vaadin-grid-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/528)
> Bump to 3.1-SNAPSHOT and Flow 1.5-SNAPSHOT

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridComponentRendererIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandCollapseRecursivelyIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenu.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenuTest.java
Fixes #458
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/500)
> Correct setTarget behavior for null

- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
Connected to vaadin/vaadin-grid#1523
Align with the changes from vaadin/vaadin-grid@bbd821b89b71652c38d2d47f9f2da73b19dc446d
Note: for the 3.x version only (web component ^5.3.0), does not need to be cherry-picked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/520)
> Update vaadin-grid-flow-selection-column width

- vaadin-grid-flow/pom.xml
Updates
- vaadin-lumo-styles to 1.4.1
- vaadin-checkbox to 2.2.6
- vaadin-control-state-mixin to 2.1.2
- vaadin-themable-mixin to 1.4.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/532)
> Version updates

- src/main/java/com/vaadin/flow/component/grid/GridContextMenu.java
- src/test/java/com/vaadin/flow/component/grid/GridContextMenuTest.java
- src/test/java/com/vaadin/flow/component/grid/it/ContextMenuGridIT.java
- src/test/java/com/vaadin/flow/component/grid/it/ContextMenuGridPage.java
- src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
- src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridComponentRendererIT.java
- src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandCollapseRecursivelyIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/540)
> Correct setTarget behavior for null (#500)

- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
- vaadin-grid-flow-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java
- vaadin-grid-flow-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridTHTDElement.java
- vaadin-grid-flow-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridTRElement.java
Cherry picked from vaadin/vaadin-components-testbench#70
Also added test using TBElement api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/537)
> Fix GridTRElement select for single select grid

- README.md
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridComponentRendererIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandCollapseRecursivelyIT.java
- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenu.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenuTest.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/editor/EditorImplTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/542)
> 3.0.1 cherry picks

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridEditorFocusPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridEditorFocusIT.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Resolves #511
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/531)
> flushing _debounceIncreasePool if it is available

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/HiddenColumnPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/543)
> Fix typos in tests

- vaadin-grid-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/541)
> Patch version updates

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridEditorFocusPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/HiddenColumnPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridEditorFocusIT.java
- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/545)
> 3.0.2 cherry picks

- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes #509 
This is a simpler alternative and less intrusive than #508
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/510)
> fix connector so as it works in Polymer 3

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/566)
> 3.0 cherry picks

- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridSelectIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java
Fixes [vaadin/vaadin-grid-flow/issues/506](https://github.com/vaadin/vaadin-grid-flow/issues/506)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/554)
> 506 treegrid multiselect exception

- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/BeanGridTest.java
Fixes #553
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/556)
> Add field and getter for beanType

- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/569)
> Add vaadin-grid-flow-selection-column component for P3

- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/573)
> 506 treegrid multiselect exception (#554)

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridDelegateFocusToComponentPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDelegateFocusToComponentIT.java
Testing changes on [PR #5142](https://github.com/vaadin/flow/pull/5142) to fix issue [#4191](https://github.com/vaadin/flow/issues/4191)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/564)
> IT for focusing components inside grid cells using keyboard (flow #4191)

- src/test/java/com/vaadin/flow/component/grid/it/GridDelegateFocusToComponentIT.java
- src/test/java/com/vaadin/flow/component/grid/it/GridDelegateFocusToComponentPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/583)
> IT for focusing components inside grid cells using keyboard (#564)

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
Fixes #568
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/602)
> Change the validator logic in the demo

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
Fixes #568
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/610)
> Change the validator logic in the demo (#602)

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DragAndDropGridPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DragAndDropGridIT.java
- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dnd/GridDragStartEvent.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dnd/GridDropEvent.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Also, bump webjar to 5.4.0-alpha4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/630)
> Dnd selection drag details

- vaadin-grid-flow-integration-tests/pom.xml
- vaadin-grid-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/633)
> Make TB artifactId consistent with other components

- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/637)
> Add polyfill for iOS devices

- vaadin-grid-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/639)
> Pin dependency versions

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/641)
> Add prerelease repo to be able to release Grid properly

- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/642)
> Fix the HeaderFooterTest to not use common package

- vaadin-grid-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/645)
> Update webjar dependencies

- pom.xml
- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/647)
> Update Grid version and use property for context menu version

- vaadin-grid-flow-demo/pom.xml
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Related with https://github.com/vaadin/flow/issues/5696
Fixes https://github.com/vaadin/flow/issues/5706
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/650)
> Fix connector when runing in bower mode for Safari and FF

- vaadin-grid-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/653)
> Remove vaadin-components-testbench

- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/659)
> Update WC versions

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/AddingColumnsPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/AddingColumnsIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Fix #587 
Added test cases for each kind of Renderer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/679)
> Reset DataCommunicator after configuring new Column

- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/686)
> Bump wc version to 5.4.5

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridRefreshAllPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridRefreshAllIT.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fix #589 (see comment in the ticket for explanation)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/688)
> Add caching of subcache sizes in connector

- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/697)
> Bump versions, update WC dependency to 5.4.6

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridTestPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridDetachAttachPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestPageIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridDetachAttachIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
Fix #539
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/700)
> Reset requested range on ArrayUpdater.init

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ItemClickListenerPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ItemClickListenerIT.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fix #702
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/703)
> Prevent ItemClickEvents on focusable components

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridStylingPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridStylingIT.java
Connected to #717 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/718)
> Add test for #717

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/PreserveOnRefreshPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/PreserveOnRefreshIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java
Fix #692
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/728)
> Render header and footer on attach

- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/AbstractNoW3c.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DynamicEditorKBNavigationIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/HiddenColumnIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ItemClickListenerIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/UpdateEditorComponentIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/AbstractTreeGridIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/744)
> Disable the w3c communication mode for remote tests. (#674)

- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/745)
> Update webcomponent to 5.4.8

- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridMultiSelectionModelTest.java
fixes #638 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/743)
> Use id from data provider in selection

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DisabledGridPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DisabledGridIT.java
Part of #687
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/750)
> IT test for #687 and vaadin/flow#6315 PR.

- vaadin-grid-flow/pom.xml
Fixes #761
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/762)
> Use a new version for vaadin-text-feild for Grid.

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridRefreshAllPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridRefreshAllIT.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
fix #740
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/769)
> Refresh grid's effectiveSize on data updates

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ColumnResizeEventPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ColumnResizeIT.java
- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ColumnResizeEvent.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/746)
> Adds column resize event and listener

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/LazyHierarchicalDataProvider.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridRefreshAllPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridRefreshAllIT.java
The issue got fixed in PR #769
Close #499
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/773)
> Add test for TreeGrid bug #499

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridTestScrollingOver100kLines.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestScrollingOver100kLinesIT.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes #578 
Fixes #737 
Fixes #741 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/777)
> Fixes row loading issue when scrolling over 100k rows

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridTestScrollingOver100kLines.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestScrollingOver100kLinesIT.java
- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Connected to vaadin/vaadin-grid#1660
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/779)
> Bump grid wc version

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridScrollToPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridScrollToIT.java
- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Fixes #618
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/778)
> Add API for scrolling to index/start/end

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ColumnResizeEventPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ColumnResizeIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ColumnResizeEvent.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/783)
> Synchroniz width and flex-grow on col resize. Remove values from event.

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridSingleSelectionPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSingleSelectionIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes #713
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/781)
> Implement setDeselectAllowed

- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/795)
> Bump WC to 5.5.0

- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/796)
> Bump webcomponent version to 5.4.11

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/798)
> Bump to Flow 2.1-SNAPSHOT

- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractRow.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/FooterRow.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridNoneSelectionModel.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/HeaderRow.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
Connected to https://github.com/vaadin/components-team-tasks/issues/483
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/805)
> Update exceptions wording

- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDetailsRowIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeComponentColumnsIT.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes #787
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/800)
> Fix component renderers update

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridOrderColumnsPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridTestPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestPageIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ColumnReorderEvent.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes #810
Closes #804 
Closes #806 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/809)
> Include all columns to column reorder event

- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/821)
> Bump vaadin-grid version

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridTestPage.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridColumnOrderHelper.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes #820
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/823)
> Fix column reordering on multiselect mode

- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Connected to https://github.com/vaadin/components-team-tasks/issues/479
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/724)
> Improve error handling in connector: wrap with try catch

- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridSerializableTest.java
Added tests and fixes to #841
Fixes: #839
> Fix serialization with test

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js
cherry-pick to merge to 4.1.
Fixes #660
> Cherry pick/width selection column adapts to check box

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandAllPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandAllIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Fixes in WC but the original bug in Flow-component. So the test is to reproduce the bug in Flow-Component.
Fixes #855
> Bump WC version and add a test

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/SortingPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Cherry-pick/merge the commit: Fixes #747 to 4.1
Fixes #747
> Fixes: Reattaching a Grid resets its sort order #747 (#873)

- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
> Fix typo in parameter name

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
> Restore Grid setClassNameGenerator example

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Co-authored-by: Guille <alvarezguille@users.noreply.github.com>
> docs: Document heightByRows performance implications (#919)

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridSetItemsAfterDetachPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridSetItemsAfterDetachIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
> Delay call to connector method

- pom.xml
- vaadin-grid-flow-demo/pom.xml
- vaadin-grid-flow-integration-tests/pom-bower-mode.xml
- vaadin-grid-flow-integration-tests/pom.xml
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/HiddenColumnIT.java
- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
* Bump snapshot version
* Bump flow-component-base (2.3-SNAPSHOT)
* Bump WC dependency
* Bump webjar dependencies
Part of vaadin/components-team-tasks#534
> Bump versions for 14.3

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/PersonData.java
> Use the correct constructor for creating complete Person instances

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
Fixes https://github.com/vaadin/vaadin-grid-flow/issues/974 https://github.com/vaadin/90min-dx-tasks/issues/167
> Fix ArrayIndexOutOfBoundsException in demo

- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridDataController.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridListDataView.java
Take into use the add and remove
methods added to flow-data
AbstractListDataView.
part of vaadin/flow#8382
> Use provided manipulation methods

- vaadin-grid-flow/pom.xml
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridListDataViewTest.java
> Validate that size changes are fired.

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/PersonData.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridListDataViewPage.java
Use the size event to update
item set size.
> Use the size event to update label

- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridListDataView.java
> Use abstract method implementations

- vaadin-grid-flow-integration-tests/benchmark/run-benchmark.js
Fixes https://github.com/vaadin/components-team-tasks/issues/545
> Submit the benchmark results to Google Spreadsheet

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridListDataViewPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridListDataViewIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridDataView.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridListDataView.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridListDataViewTest.java
Added getItemRow
part of vaadin/flow#8497
> Remove currentItem and items

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridListDataViewPage.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridDataViewImpl.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridDataViewImplTest.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridListDataViewTest.java
> Use setDataSource for setting data.

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridDataProviderSize.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDataProviderSizeIT.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
> Optimize sorting request (#1025)

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
Use add for moving item in list
> Update drag and drop demo

- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridDataViewImpl.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridListDataView.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridDataViewImplTest.java
Depends on https://github.com/vaadin/flow/pull/8581
> Configure identity provider for a components through the Data View

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ChangingDataSizePage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridListDataViewPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/TemplatedColumnsPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/dataview/AbstractRowCountGridPage.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridDataViewImplTest.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridListDataViewTest.java
> Use setItems instead of setDataSource

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridListDataViewPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/dataview/AbstractItemCountGridPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/dataview/ItemCountCallbackGridPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/dataview/ItemCountEstimateGridPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/dataview/ItemCountEstimateStepGridPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/dataview/ItemCountUnknownGridPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/i/dataview/AbstractItemCountGridIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/i/dataview/ItemCountCallbackGridIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/i/dataview/ItemCountEstimateGridIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/i/dataview/ItemCountEstimateStepGridIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/i/dataview/ItemCountUnknownGridIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridDataViewImpl.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridListDataView.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridDataViewImplTest.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridListDataViewTest.java
> Use ItemCount instead of size and RowCount #8651

- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/dataview/AbstractItemCountGridIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/dataview/ItemCountCallbackGridIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/dataview/ItemCountEstimateGridIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/dataview/ItemCountEstimateStepGridIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/dataview/ItemCountUnknownGridIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridDataViewImpl.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridDataViewImplTest.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridListDataViewTest.java
> Move contains to GridListDataView

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
> Rework filtering example

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridScrollToPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridScrollToIT.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
> fix: delay call to client in scrollToEnd (#1062)

- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
Fixes https://github.com/vaadin/vaadin-grid-flow/issues/1007
> Add desc sort example

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridListDataViewPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridListDataViewIT.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridDataViewTest.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridListDataViewTest.java
Generic data view unit test is moved to Flow, data view IT tests is supplemented with add/remove/update cases.
Depends on https://github.com/vaadin/flow/pull/8639
> Grid data view tests supplement

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/dataview/AbstractItemCountGridPage.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridDataView.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridLazyDataView.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/dataview/GridListDataView.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridDataViewTest.java
- vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridLazyDataViewTest.java
These changes in Grid tied with this Data View API updates in Flow https://github.com/vaadin/flow/pull/8874
> Filter support in Data View API

- vaadin-grid-flow-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java
- vaadin-grid-flow-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/TreeGridElement.java
Fixes https://github.com/vaadin/vaadin-grid-flow/issues/1115
> fix: check for connector before using it

- vaadin-grid-flow-integration-tests/frontend/src/grid-on-client-and-slot.js
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridOnClientAndSlot.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridOnClientAndSlotPage.java
- vaadin-grid-flow-integration-tests/src/main/webapp/frontend/src/grid-on-client-and-slot.html
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridOnClientAndServerIT.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
> fix: prevent NPE for client-side only grids (#1111)

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridLoadsItemsPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridChangingHierarchyPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridEmptyPage.java
- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridHugeTreePage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/GridLoadsItemsIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestScrollingOver100kLinesIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridEmptyIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridHugeTreeIT.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridHugeTreeNavigationIT.java
- vaadin-grid-flow-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/GridElement.java
- vaadin-grid-flow-testbench/src/main/java/com/vaadin/flow/component/grid/testbench/TreeGridElement.java
- vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Cherry pick
- Perf/unnecessary page calls (#1084)
- Connector cleanup (#1108)
- fix: check for connector before using it (#1116)
- fix: prevent possible memory leak (#1102)
> Cherry-pick #1084, #1108, #1116, #1102

- vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridOnClientAndSlotPage.java
- vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridOnClientAndServerIT.java
- vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
> fix: make connector patch ItemCache only once (#1128)

- vaadin-grid-flow-demo/pom.xml
- vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
This is a fix for the demo issue described in #1122.
> docs: use focus-target in filtering demo
