pom.xml, src/main/java/com/vaadin/ui/grid/AbstractColumn.java, src/main/java/com/vaadin/ui/grid/Grid.java, src/main/java/com/vaadin/ui/grid/GridTemplateRendererUtil.java, src/main/resources/META-INF/resources/frontend/flow-grid-component-renderer.html, src/main/resources/META-INF/resources/frontend/gridConnector.js, src/test/java/com/vaadin/ui/grid/tests/GridIT.java, src/test/java/com/vaadin/ui/grid/tests/GridTestPage.java, src/test/java/com/vaadin/ui/grid/tests/GridTestPageIT.java
This patch requires the changes made in Flow for the same feature. See https://github.com/vaadin/flow/pull/3116.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/40)
=> Make ComponentRenderers use virtual children

src/main/java/com/vaadin/ui/grid/Grid.java, src/main/resources/META-INF/resources/frontend/flow-grid-component-renderer.html, src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
Added missing imports to vaadin-grid-flow-selection-column
and flow-grid-component-renderer. Without correct imports
polymer bundler will not be able to correctly order the bundled code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/42)
=> Add missing html imports

src/main/java/com/vaadin/ui/grid/Grid.java, src/test/java/com/vaadin/ui/grid/demo/GridView.java, src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java, src/test/java/com/vaadin/ui/grid/tests/GridIT.java, src/test/java/com/vaadin/ui/grid/tests/Person.java
Implemented the so-called BeanGrid feature: Added a constructor for Grid that takes a bean-type as it's parameter and automatically adds columns for each of the bean's properties. Also added addColumn(String) method for easily creating columns for sub-properties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/38)
=> Make Grid add columns based on bean properties

src/main/java/com/vaadin/ui/grid/GridTemplateRendererUtil.java, src/main/resources/META-INF/resources/frontend/flow-grid-component-renderer.html, src/test/java/com/vaadin/ui/grid/it/GridItemRefreshPage.java, src/test/java/com/vaadin/ui/grid/it/GridItemRefreshPageIT.java
Depends on changes made on flow. See https://github.com/vaadin/flow/pull/3157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/45)
=> Fix for DataProvider/Communicator refreshAll when using components.

src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java, src/main/java/com/vaadin/flow/component/grid/Grid.java, src/main/java/com/vaadin/flow/component/grid/GridTemplateRendererUtil.java, src/main/resources/META-INF/resources/frontend/gridConnector.js, src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, src/test/java/com/vaadin/flow/component/grid/tests/GridIT.java, src/test/java/com/vaadin/flow/component/grid/tests/GridTestPage.java, src/test/java/com/vaadin/flow/component/grid/tests/GridTestPageIT.java
In my tests there weren't any duplicated data as the ticket suggest - but a high load of unnecessary data sent from the server. That data is related to the item details - basically Grid was sending the data (and the components) related to item details for every item in the Grid, even when the details weren't shown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/51)
=> Fix Grid to send item details data only when the details are actually open

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/main/resources/META-INF/resources/frontend/gridConnector.js, src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, src/test/java/com/vaadin/flow/component/grid/tests/GridIT.java
Add getter and setter for `detailsVisibleOnClick`, which has a default value of `true`. The demo for details row is separated to it's own tab and there are now two demos: the first one demonstrates only the default functionality with details opening by clicking on rows, and the second one disables this and opens details with the server-side API. Also, changed mentions of "details row" to "item details" in the demo, since this is the API naming we're using.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/53)
=> Allow disabling opening item details by clicking on rows

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/test/java/com/vaadin/flow/component/grid/it/GridPageSizePage.java, src/test/java/com/vaadin/flow/component/grid/it/GridPageSizePageIT.java
This is a workaround for the actual problem. The workaround should be applied until the underlying bug on the element is fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/76)
=> Renabled the pageSize setting for Grid

src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java, src/main/java/com/vaadin/flow/component/grid/Grid.java
Instead of always creating new `<template>` elements, reuse the old one if such is already created.
In addition to increasing performance, this also allows changing the header and footer after once set, because previously it would just have added new templates next to the existing ones, and the existing template would still have been used for the header/footer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/92)
=> Reuse templates for header, footer and details

src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java, src/main/java/com/vaadin/flow/component/grid/AbstractGridSingleSelectionModel.java, src/main/java/com/vaadin/flow/component/grid/Grid.java, src/main/resources/META-INF/resources/frontend/gridConnector.js, src/test/java/com/vaadin/flow/component/grid/it/GridTestPage.java, src/test/java/com/vaadin/flow/component/grid/it/GridTestPageIT.java, src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
This fix uses the refactored beforeClientResponse mechanism in Flow. Depends on https://github.com/vaadin/flow/pull/3617
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/105)
=> Fix Grid state when reattaching it to the tree

pom.xml, src/main/java/com/vaadin/flow/component/grid/Grid.java, src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Update Grid webjar to 5.0.0.beta3. Add support for the heightByRows flag, and add a demo for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/108)
=> Add support for heightByRows

src/main/resources/META-INF/resources/frontend/gridConnector.js
This will reduce the server-side memory consumption, since less pages will be requested at a time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/99)
=> Refactor the logic behind the extraPageBuffer to consider visible rows instead

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/main/resources/META-INF/resources/frontend/gridConnector.js, src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, src/test/java/com/vaadin/flow/component/grid/it/DisabledGridIT.java, src/test/java/com/vaadin/flow/component/grid/it/DisabledGridPage.java, src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Disabled Grids don't allow selection, expand/collapse of details rows and all input/selection elements inside it are disabled (they don't fire events to the server). But scrolling through the items still work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/148)
=> Add support for disabled Grid

src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java, src/main/java/com/vaadin/flow/component/grid/Grid.java, src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPage.java, src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
Also ignore events from hidden selectAll checkboxes on the server-side.
Fix #73.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/154)
=> Revalidate the state of the selectAll checkbox on DataProvider change

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/main/java/com/vaadin/flow/component/grid/GridSorterComponentRenderer.java, src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java, src/test/java/com/vaadin/flow/component/grid/testbench/GridElement.java
This patch fixes the problem introduced with the BasicRenderers rework, that prevented headers to be sortable when Components (and ComponentRenderers) are used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/159)
=> Fix the sorting when Components are used in the header

src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java, src/main/java/com/vaadin/flow/component/grid/Grid.java, src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java, src/test/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowIT.java, src/test/java/com/vaadin/flow/component/grid/it/GridHeaderRowWithComponentsIT.java, src/test/java/com/vaadin/flow/component/grid/it/GridHeaderRowWithComponentsPage.java
Instead of applying ComponentRenderer for headers every time the
renderer is changed, apply the current renderer beforeClientResponse so
that only the last renderer is used.
Fix #172
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/176)
=> Render header components only once in a roundtrip

src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java, src/main/java/com/vaadin/flow/component/grid/ColumnBase.java, src/main/java/com/vaadin/flow/component/grid/ColumnGroup.java, src/main/java/com/vaadin/flow/component/grid/ColumnLayer.java, src/main/java/com/vaadin/flow/component/grid/Grid.java, src/main/java/com/vaadin/flow/component/grid/GridSorterComponentRenderer.java, src/main/java/com/vaadin/flow/component/grid/HeaderRow.java, src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java, src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, src/test/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowIT.java, src/test/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowPage.java, src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
for having sorting indicators and as the target of Column::setHeader.
Filtering row is added to the "Basic features" demo now that the sorting indicators don't go always to the bottom row.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/181)
=> Use the first created HeaderRow as the default

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java, src/test/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowIT.java, src/test/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowPage.java
The logic for checking empty column-groups was to check that
childCount==0, but that worked only before first rendering (before
templates were attached beforeClientResponse). Now it checks if there
are no column or column-group children.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/202)
=> Fix removing empty column-groups after initial rendering

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/test/java/com/vaadin/flow/component/grid/BeanGridTest.java, src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
and improve javadocs of the bean-grid constructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/217)
=> Use alphabetical order for bean-grid columns by default

src/main/resources/META-INF/resources/frontend/gridConnector.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/220)
=> Fix some connector parts so that they are compatible with IE11

src/test/java/com/vaadin/flow/component/grid/it/ButtonInGridIT.java, src/test/java/com/vaadin/flow/component/grid/it/ButtonInGridPage.java
IT verification test for #122.
Closes #122.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/221)
=> Provide an IT test to click Vaadin button inside Grid via space

src/main/resources/META-INF/resources/frontend/gridConnector.js, src/test/java/com/vaadin/flow/component/grid/it/ButtonInGridIT.java, src/test/java/com/vaadin/flow/component/grid/testbench/TreeGridElement.java, src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridComponentRendererIT.java, src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridComponentRendererPage.java
Problem occurs when expanding item. Only expanded visible items are updated properly because those are new items. Already existing visible components may be lost when their row index changes. Call to _attachRenderedComponentIfAble function explicitly in _updateItem makes sure that component is re-attached.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/232)
=> Fixed component renderer content not being updated in TreeGrid

src/test/java/com/vaadin/flow/component/grid/it/ButtonInGridIT.java
A part of fix for #122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/227)
=> Enable IT test for clicking a button inside Grid via keyboard

src/main/resources/META-INF/resources/frontend/gridConnector.js
This way we update the serverside sorting always after the
sorter-changed event has been handled by grid.
Fixes #188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/249)
=> Observe changes in _previousSorters instead of using an eventListener.

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/test/java/com/vaadin/flow/component/grid/GridColumnTest.java
Added a javadoc comment saying `getRenderer` return value shouldn't be modified after Grid has been rendered
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/254)
=> Add javadoc to Renderer getters

README.md, pom.xml, src/main/java/com/vaadin/flow/component/grid/Grid.java, src/main/java/com/vaadin/flow/component/grid/GridVariant.java, src/test/java/com/vaadin/flow/component/treegrid/it/AbstractTreeGridIT.java, src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridHugeTreeIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/245)
=> Update support for material theme and theme variant

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/main/resources/META-INF/resources/frontend/gridConnector.js, src/test/java/com/vaadin/flow/component/grid/GridColumnTest.java, src/test/java/com/vaadin/flow/component/grid/it/ButtonInGridIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/259)
=> Maintenance release picks

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/main/java/com/vaadin/flow/component/grid/GridArrayUpdater.java, src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java, src/main/java/com/vaadin/flow/component/treegrid/TreeGridArrayUpdater.java
Depends on https://github.com/vaadin/flow/pull/4427
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/275)
=> Update Grid to work with the new abstraction of HierarchicalArrayUpdater

src/test/java/com/vaadin/flow/component/grid/it/GridWithTemplateIT.java
The issue #71 was fixed by the changes introduced with
https://github.com/vaadin/flow/pull/4459
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/294)
=> Enable test after fix in Flow

src/test/java/com/vaadin/flow/component/grid/it/GridWithTemplateIT.java
The issue #71 was fixed by the changes introduced with
https://github.com/vaadin/flow/pull/4459
Cherry-picked from master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/296)
=> Enable test after fix in Flow (#294)

src/main/resources/META-INF/resources/frontend/gridConnector.js
* Observe changes in _previousSorters instead of using an eventListener.
This way we update the serverside sorting always after the
sorter-changed event has been handled by grid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/304)
=> Observe changes in _previousSorters instead of using an eventListener (#249)

src/main/java/com/vaadin/flow/component/grid/Grid.java
added formatting to getRenderer Javadoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/312)
=> getRenderer Javadoc formatting

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/test/java/com/vaadin/flow/component/grid/it/DetailsGridIT.java, src/test/java/com/vaadin/flow/component/grid/it/DetailsGridPage.java, src/test/java/com/vaadin/flow/component/grid/it/GridWithTemplatePage.java
Remove deprecated `new Element(String, boolean)` usage.
Fixes #376
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/377)
=> Fix details generator clearing when reusing details component.

src/main/resources/META-INF/resources/frontend/gridConnector.js, src/test/java/com/vaadin/flow/component/grid/it/GridLoadsItemsIT.java, src/test/java/com/vaadin/flow/component/grid/testbench/GridElement.java, src/test/java/com/vaadin/flow/component/grid/testbench/GridTRElement.java, src/test/java/com/vaadin/flow/component/grid/testbench/TreeGridElement.java
There was a bug in vaadin-grid 5.2.0 that prevented some of the tests to
work. That was fixed on 5.2.1. Some other fixes on the connector and the
tests had to be made, due to behavior changes of the webcomponent.
The build will only pass after https://github.com/vaadin/flow-component-base/pull/91 has been merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/384)
=> Fix tests and connector to properly support grid 5.2.1

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/test/java/com/vaadin/flow/component/grid/GridColumnTest.java
Giving devs the opportunity to extend Grid.Column and let Grid return that overriden class to provide new column functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/381)
=> Fix for https://github.com/vaadin/flow/issues/4654

src/main/resources/META-INF/resources/frontend/gridConnector.js, src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
Disable switching of multiselect selectAll button
when grid disabled.
Fixes #379
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/400)
=> Fix client side visual de-selection for disabled grid.

pom.xml, src/test/java/com/vaadin/flow/component/grid/LazyHierarchicalDataProvider.java, src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, src/test/java/com/vaadin/flow/component/grid/demo/HierarchicalTestBean.java, src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridBasicFeaturesPage.java, src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridScrollingPage.java
Moving the Bean to the demo package as it's
used in the demo and other tests can use it from there
also as needed.
This will make the demo build much less brittle due to
changes to the parent project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/427)
=> Move HierarchicalTestBean to demo package.

pom.xml, src/test/java/com/vaadin/flow/component/grid/LazyHierarchicalDataProvider.java, src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, src/test/java/com/vaadin/flow/component/grid/demo/HierarchicalTestBean.java, src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridBasicFeaturesPage.java, src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridScrollingPage.java
Moving the Bean to the demo package as it's
used in the demo and other tests can use it from there
also as needed.
This will make the demo build much less brittle due to
changes to the parent project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/428)
=> Move HierarchicalTestBean to demo package. (#427)

src/main/java/com/vaadin/flow/component/grid/ColumnPathRenderer.java, src/main/java/com/vaadin/flow/component/grid/Grid.java, src/main/java/com/vaadin/flow/component/grid/editor/EditorRenderer.java, src/main/resources/META-INF/resources/frontend/gridConnector.js, src/test/java/com/vaadin/flow/component/grid/it/ColumnPathIT.java, src/test/java/com/vaadin/flow/component/grid/it/ColumnPathPage.java
* Support for the path property when using ValueProviders 
* Fix context menu issues when using column path property 
* Update patch to be backportable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/429)
=> Add support for the path property on Columns (#411)

src/main/resources/META-INF/resources/frontend/gridConnector.js, src/test/java/com/vaadin/flow/component/grid/it/GridFilteringIT.java
Fix the failing ITs (also the one about filtering)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/441)
=> Properly clear client caches when collapsing TreeGrid

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java, src/main/resources/META-INF/resources/frontend/gridConnector.js, src/test/java/com/vaadin/flow/component/grid/it/GridItemRefreshPage.java, src/test/java/com/vaadin/flow/component/grid/it/GridItemRefreshPageIT.java
Update only refreshed items in the DOM instead of all items every single
time and multiple times per each update. grid._assignModels(...) now takes
the updated items, when called without parameters, it refreshes every
single row. This has caused some performance overhead for slower
browsers.
Fixes #419
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/485)
=> Fix unnecessary DOM updates for grid

pom.xml, src/main/java/com/vaadin/flow/component/grid/ColumnPathRenderer.java, src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, src/test/java/com/vaadin/flow/component/grid/it/GridPageSizePageIT.java, src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
No header row should be added if not defining column header(s).
fixes the issue #477 for v12 version as this is only for 5.2.7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/482)
=> Fix visible empty header

src/main/java/com/vaadin/flow/component/grid/Grid.java, src/test/java/com/vaadin/flow/component/grid/BeanGridTest.java
Added back a handy shorthand that existed in Vaadin 8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/494)
=> Added a shorthand to remove all components

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java
Double-clicking on rows in Unbuffered dynamic editor demo caused ever-increasing delays to opening the editor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/548)
=> Refresh on client-side events only

vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/517)
=> Fixes #516 and #515

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/TextInsideComponentRendererPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/TextInsideComponentRendererIT.java
Test for flow#5206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/577)
=> Add a test tht checks that flow-component-renderer doesn't throw if text node is used

pom.xml, vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenuTest.java
One unit test needed more mocking because of internal changes in
ContextMenuBase::setTarget
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/596)
=> Bump context-menu version and update tests

vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java, vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ColumnAutoWidthPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ColumnAutoWidthIT.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
New feature for automatically setting the width of a column based on the column contents. For more info see the new demo "Configuring columns / Columns with automatic width" and the Javadoc of `Column#setAutoWidth(boolean)`.
Fixes #619
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/623)
=> feat: column auto-width

pom.xml, vaadin-grid-flow-integration-tests/pom-bower-mode.xml, vaadin-grid-flow-integration-tests/pom.xml, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/AbstractNoW3c.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridIT.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DynamicEditorKBNavigationIT.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/HiddenColumnIT.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ItemClickListenerIT.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/UpdateEditorComponentIT.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/AbstractTreeGridIT.java
To fix grid tests we should get w3c communication mode disabled
for the chrome browser.
Fixes #673 
Needs new ticket for disabling functionality the w3c compatibility is fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/674)
=> Disable the w3c communication mode for remote tests.

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/SortingPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java, vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Updating the client-side sorters needed to be postponed, because the
sorter elements were not present at the time of this JS execution when
done on the same roundtrip as creating/attaching the grid. The grid
would finalize its initialization afterwards with empty sort orders,
causing un-sorted data to be requested from the server.
Also, the initial call to the sorter observer needed to be disabled so
it doesn't reset the sort order.
Fix #13
Fix #465 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/672)
=> Fix setting initial sort order

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridStylingPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridStylingIT.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestPageIT.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Using the map already needed a lot of code to keep it up to date, and in
order to solve #684, more logic would've been needed to maintain it also
when grid/columns are re-attached to the DOM. Saving the column ids as
properties makes Flow take care of this automatically.
Fix #684
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/695)
=> Replace $connector.columnToIdMap with properties

vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
With the proper web component API to retrieve item and column data from
events, we can reduce the amount of code, complexity and usage of
private APIs.
Fix #439
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/608)
=> Refactor gridConnector to use getEventContext API

vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
In the pull request #556 I forgot to set the beanType in the protected Grid Constructor. This commit also adds it there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/681)
=> Also set beanType in protected Grid constructor

vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
If I have a column with a ClassNameGenerator in a Grid where I also have a DetailsRenderer,
The code accesses the ClassNameGenerator-method with an undefined column. This is a solution to that problem.
It might be a bandaid on another problem, but it at least solves it.
(This is my first pull-request ever, tell me if I do something wrong)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/717)
=> DetailsRenderer and ClassNameGenerator in the same Grid fails

vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java
Part of the multiselection performance improvements #451.
This decreases both the space complexity of the update message sent from server to client, as well as the time complexity of the client-side execution, from linear _O(N)_ to constant _O(1)_, where _N_ is number of items to select/deselect (when _N_ is larger than the number of items present at client-side).
This doesn't affect the server-side performance, which still operates on the full data set on `selectAll`.
Testing the performance of  `selectAll` before the fix (still including the previous perfo fix in #715) and after, with 1,000 items and 10,000 `String` items:
|                                     | Before  | After |
|-------------------------------------|---------:|-------:|
| 1k items: time from click to paint including …
=> Multiselect perf: send updates only to loaded items

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridDetailsRowPage.java, vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridDetailsRowPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDetailsRowIT.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridDetailsRowIT.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridHugeTreeIT.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
This pull request fixes:
- #701 
and #525  (PR: https://github.com/vaadin/vaadin-grid-flow/pull/731 )
The cache was not clear correctly when a node is collapsed. So it was not rebuilt when the node expands.
There may be a better way to clear the cache.
Requires this change ( vaadin/flow#6144 ) to be merged in flow or the details will displayed but empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/732)
=> Treegrid details is not working after collapse then expand a node

pom.xml, vaadin-grid-flow-demo/pom.xml, vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java, vaadin-grid-flow-integration-tests/pom-bower-mode.xml, vaadin-grid-flow-integration-tests/pom.xml, vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridTestPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridTestPageIT.java, vaadin-grid-flow-testbench/pom.xml, vaadin-grid-flow/pom.xml, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ColumnReorderEvent.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
The PR adds the `ColumnReorderEvent` class and `Grid.addColumnReorderListener()`. I've also implemented a demo page in GridDemo.
Fixes https://github.com/vaadin/vaadin-grid-flow/issues/755.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/756)
=> Add support for listening for column-reorder event from the server-side

vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java, vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ItemClickListenerPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/ItemClickListenerIT.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ItemClickEvent.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ItemDoubleClickEvent.java, vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Added a method to ItemClickListener. It works by passing the id of the column to the event and then discovering the column on the server side.
I used the idea from the workaround by @pekam in https://vaadin.com/forum/thread/17585345/17586229 - but also used internal `flowId` of the column to get it when the user forgets to set the id.
Simple tests included.
Closes #725
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/780)
=> ItemClickListener.getColumn

vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenu.java
to prevent returning null values from the function.
Formatting changes are in a separate commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/784)
=> Change dynamicContentHandler type to SerializablePredicate

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridOrderColumnsPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridOrderColumnsIT.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridColumnOrderHelper.java
Fixes a DX test finding: "If the columns are already physically in correct order in the dom, the column reorder doesn't have any effect even if the columns are visually in different order"
Note that the first commit in this PR is just about autoformatted lines. The meaningful changes are in the second commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/786)
=> Fix column visual reorder

vaadin-grid-flow-demo/pom.xml, vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DragAndDropGridGenericPage.java, vaadin-grid-flow/pom.xml, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridDnDTest.java
Sets server side drag data and active drag source when grid is dragged.
Uses mobile dnd polyfill from DnDUtil from Flow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/797)
=> Integrate Grid DnD with Generic Flow DnD

vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
`Grid#callSelectionFunctionForItems` prepares items as a json array before sending it to connector. It creates an array of `{key: KEY}` object. When `Grid#deselectAll` is called, the former method creates an object `{key:"null"}` and that object ends up being the activeItem on client. What this changes does it to send `null` to be set on client instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/815)
=> Send null to client instead of {key:"null"} object

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridOrderColumnsPage.java, vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridOrderColumnsPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridOrderColumnsIT.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/GridColumnOrderHelper.java, vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridColumnOrderTest.java
Change the HashMap to ConcurrentHashMap.
Change the test case to throw an exception if Map is a HashMap
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/828)
=> Fix setColumnOrder if 2 header rows

vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
Since setComparator() uses Comparator as type parameter, Lambda will not be serializable. Inline SerlializableComparator class should be used instead. It would be even better to fix setComparator type parameter to be SerializableCompator, but there are additional problems to be solved before it can be made, as seen in https://github.com/vaadin/vaadin-grid-flow/pull/840
Fixes: https://github.com/vaadin/vaadin-grid-flow/issues/839
=> Replace Lambda with inline SerializableComparator

vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Connected to https://github.com/vaadin/vaadin-combo-box-flow/issues/313
Make the `Flow.tryCatchWrapper` called lazily.
=> Fix connector tryCatchWrapper definition

vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/AbstractNoW3c.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
https://github.com/vaadin/vaadin-grid-flow/pull/674 fixed an issue in
chrome driver by disabling the w3c mode. This has broken local running
of tests. This should allow the tests to run both locally and on
teamcity.
=> Fix running tests locally

vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Relates to https://github.com/vaadin/vaadin-grid-flow/issues/918
=> docs: Document heightByRows performance implications

vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Co-authored-by: Guille <alvarezguille@users.noreply.github.com>
=> docs: Document heightByRows performance implications (#919)

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridFilterExpandView.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridFilterExpandIT.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
Fixes #891.
By clearing the connector from all the pending stuff from previous
refresh, the data is not messed up by updates from outdated requests.
This seems to also help with the slowness of the updates at least to
some extent.
=> Reset TreeGrid connector on refreshAll

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridFilterExpandView.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridFilterExpandIT.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
Fixes #891.
By clearing the connector from all the pending stuff from previous
refresh, the data is not messed up by updates from outdated requests.
This seems to also help with the slowness of the updates at least to
some extent.
=> Reset TreeGrid connector on refreshAll (#950)

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridDataProviderSize.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDataProviderSizeIT.java, vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Fixes #995 
**Short description:**
In the Flows [DataCommunicator](https://github.com/vaadin/flow/blob/master/flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java) major part of the methods calls will lead to asking for [data-provider size](https://github.com/vaadin/flow/blob/2b945d6b193ddb260c92aaf9e15f69d1ca02130c/flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java#L453). 
The initial sorting in grid-flow was fixed to be done [asynchronously](https://github.com/vaadin/vaadin-grid-flow/commit/7d34f6afac1f873331c4601340d48d6171271078#diff-18fd66d51777465fec3d9be42bac947cR417). Cleaning the direction for sorters at that point of time is leading to connector calling `ClientCallable` `sortersChanged` extra time. That will `requestFlush` from …
=> Optimize sorting request

vaadin-grid-flow-integration-tests/pom.xml
Nashorn has been removed in JDK 11 so its internals cannot be used
for object memory calculation. This just excludes the problematic test
classes from compilation automatically when Java 11 is used.
=> Make project compile with Java 11

vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java, vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/ItemGenerator.java, vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/dataview/AbstractItemCountGridPage.java, vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/dataview/ItemCountEstimateIncreaseGridPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/dataview/AbstractItemCountGridIT.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/dataview/ItemCountEstimateGridIT.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/dataview/ItemCountEstimateIncreaseGridIT.java, vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/dataview/GridDataViewTest.java
Makes automatically extending grid demo more interesting.
Cleans up old terminology in tests about step instead of increase.
Part of vaadin/flow#8643
=> Adjust for ItemCountChangeEvent::isCountEstimated

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridScrollToPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridScrollToIT.java, vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
=> fix: delay call to client in scrollToEnd (#1062)

vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
...for example, the internal flag `ensureSubCacheDelay` is fixed to `true`, and I don't see why this constant would be changed anytime soon in the future, so it's pointless to have logic in the connector that only applied if the flag was `false`.
=> Connector cleanup

vaadin-grid-flow-integration-tests/frontend/src/grid-on-client-and-slot.js, vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridOnClientAndSlot.java, vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridOnClientAndSlotPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridOnClientAndServerIT.java, vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
fix #1077
`ItemCache#ensureSubCacheForScaledIndex` method is changed by `gridConnector`, so it will make any grid on the page use the new implementation. That leads to a call from undefined object in case of a grid entirely defined on the client side needs to call this method.
This change stores the original implementation and calls it when the grid doesn't have a `$connector` object.
=> fix: prevent NPE for client-side only grids

vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
=> fix: prevent possible memory leak (#1102)

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridOnClientAndSlotPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridOnClientAndServerIT.java, vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Previous fix for client and server grids on the same page was to store the original `ensureSubCacheForScaledIndex` method before it was patched by connector, but that introduced a stack overflow error after a second grid is added from the server.
This fix makes ItemCache patching to happen only once the first server grid is added, and prevents it from happening after other grids are added.
Fixes #1077
=> fix: make connector patch ItemCache only once

vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridOnClientAndSlotPage.java, vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridOnClientAndServerIT.java, vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
=> fix: make connector patch ItemCache only once (#1128)
